### ISSUE TITLE
For what version is this meant?  Errors on make.

### ISSUE THREAD

**Issue by base698** [varnishcache/libvmod-example#1]
Used Varnish 4.3 and got a different error.  Downgraded to 4.0.3 and got this error when doing make.

```
make[2]: PYTHON@: No such file or directory
```

**Comment by lkarsten** [comment]
@nigoroll I think is fallout from 4ea3aaa? In the case where @PYTHON@ isn't expanded, the first @ becomes suppress output for this rule, and then runs "PYTHON@" which isn't valid.

To answer your question @base698 , this is for the last released stable version of Varnish Cache. Currently 4.1.

I've added a basic travis-ci setup to avoid similar problems in the future.

**Comment by dridi** [comment]
I have seen this error and I recommend the `$(PYTON)` syntax instead.

Actually, whenever we are substituting a simple variable (as in `AC_SUBST` in `autoconf`) instead of raw `automake` rules I recommend `$(...)` over `@...@`).

Note that this problem doesn't exist with varnishcache/varnish-cache#2054.

**Comment by nigoroll** [comment]
@Dridi ok, but @lkarsten why would`@PYTHON`@ not get substituted if `configure` succeeds?
@base698 for use with varnish 4.0, please use the 4.0 branch of this repo
When switching branches, please make sure to clean up with `make distclean`

> Used Varnish 4.3 and got a different error

that's not particularly helpful. Also, can you please provide a full log after a fresh checkout or `make distclean`?

**Comment by dridi** [comment]
I don't know why it fails, maybe because it's at the beginning of a recipe (silent rule) so `automake` (run before `./configure`) would break the `@...@` scheme.

Also, if we use the `$(...)` syntax, the variables can be overridden on the make command line.

```
make PYTHON=/my/awesome/alternative/python
```

**Comment by nigoroll** [comment]
@base698 please re-open with more info
