### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sandeep06011991** [varnishcache/libvmod-example#4]
Varnishapi.pc does not have variable datarootdir .
datarootdir is used in autogen.sh
This is causing 
Package varnishapi was not found in the pkg-config search path.
Perhaps you should add the directory containing `varnishapi.pc'
to the PKG_CONFIG_PATH environment variable
to be thrown even though varnishapi.pc is loaded

**Comment by dridi** [comment]
I did not understand the problem, can you please describe what you are doing, the commands that you are running and the error message you get?

Also, which version of Varnish are you working with?

**Comment by sandeep06011991** [comment]
I seem to have a broken installation of varnish . It fixed when I reinstalled it

**Comment by sandeep06011991** [comment]
VMODTOOL vmod_example.vcc
Unknown option: -o
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
make: *** [vcc_example_if.c] Error 2

getting this bug on running make

**Comment by dridi** [comment]
You didn't answer my question:

> Also, which version of Varnish are you working with?

**Comment by sandeep06011991** [comment]
I was working with 3 . Now I am using 5 . Everything is working now

**Comment by dridi** [comment]
OK, thanks for letting us know.
